CC = gcc

CFLAGS = -pg -g -ggdb -Wall -O3 -DNRAND -DANTCOL
OBJS = color.o util.o antcol.o 
BIN = antcol


all: $(OBJS) 
	$(CC) -o $(BIN) $(CFLAGS) $(OBJS) -lm
	rm *.o

clean:
	rm $(OBJS) $(BIN) *~ 


