CC = gcc

CFLAGS = -pg -g -ggdb -Wall -O3 -DNRAND -DTABUCOL 
OBJS = color.o util.o tabucol.o constr_kgcp.o 
BIN = tabucol


all: $(OBJS) 
	$(CC) -o $(BIN) $(CFLAGS) $(OBJS) -lm
	rm *.o

clean:
	rm $(OBJS) $(BIN) *~ 


